
services:
  dev:
    image: golang:alpine
    volumes:
      - .:/go/src/github.com/rclone/rclone
    working_dir: /go/src/github.com/rclone/rclone
    entrypoint: /bin/bash
    environment:
      - CGO_ENABLED=0
