---
# Github Actions release for rclone
# -*- compile-command: "yamllint -f parsable build_publish_docker_plugin.yml" -*-

name: Release Build for Docker Plugin

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      manual:
        description: Manual run (bypass default conditions)
        type: boolean
        default: true

permissions:
  contents: read
  packages: write

jobs:
  build_docker_volume_plugin:
    if: inputs.manual || github.repository == 'taldx123/rclone_rd'
    name: Build docker plugin job
    runs-on: ubuntu-latest
    steps:
      - name: Free some space
        shell: bash
        run: |
          df -h .
          # Remove android SDK
          sudo rm -rf /usr/local/lib/android || true
          # Remove .net runtime
          sudo rm -rf /usr/share/dotnet || true
          df -h .
      - name: Checkout master
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Build and publish docker plugin
        shell: bash
        run: |
          VER=${GITHUB_REF#refs/tags/}
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
              export PLUGIN_BASE_TAG=latest
          else
              export PLUGIN_BASE_TAG=master
          fi
          PLUGIN_USER=ghcr.io/taldx123
          docker login ghcr.io --username ${{ github.actor }} \
                       --password-stdin <<< "${{ secrets.GITHUB_TOKEN }}"
          for PLUGIN_ARCH in amd64 arm64 arm/v7 arm/v6 ;do
              export PLUGIN_USER PLUGIN_ARCH
              make docker-plugin PLUGIN_TAG=${PLUGIN_ARCH/\//-}
              make docker-plugin PLUGIN_TAG=${PLUGIN_ARCH/\//-}-master
          done
          make docker-plugin PLUGIN_ARCH=amd64 PLUGIN_TAG=latest
          make docker-plugin PLUGIN_ARCH=amd64 PLUGIN_TAG=master
